version: '3.8'

services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data 
  
  pgadmin:
    image: fenglc/pgadmin4
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - 5050:5050